"""initial schema

Revision ID: 6aec0d8001e0
Revises: 
Created: 2026-08-18 20:15:31.883305
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '6aec0d8001e0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('is_student', sa.Boolean(), nullable=False),
    sa.Column('is_muhaffiz', sa.Boolean(), nullable=False),
    sa.Column('email_notifications', sa.Boolean(), nullable=False),
    sa.Column('reminder_hour', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('muhaffiz_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('dedupe_key', sa.String(length=160), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('emailed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'dedupe_key', name='uq_notification_dedupe')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index('ix_notification_user_unread', ['user_id', 'read_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    op.create_table('student_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('marhala', sa.Integer(), nullable=False),
    sa.Column('current_juz', sa.Integer(), nullable=False),
    sa.Column('daily_minutes', sa.Integer(), nullable=False),
    sa.Column('active_days', sa.String(length=7), nullable=False),
    sa.Column('preferred_method', sa.Integer(), nullable=False),
    sa.Column('wake_hour', sa.Integer(), nullable=False),
    sa.Column('evening_hour', sa.Integer(), nullable=False),
    sa.Column('juz_order', sa.String(length=120), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('muhaffiz_id', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(length=16), nullable=False),
    sa.Column('juz', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['muhaffiz_id'], ['muhaffiz_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.create_index('ix_assignment_muhaffiz', ['muhaffiz_id', 'status'], unique=False)
        batch_op.create_index('ix_assignment_student_stage', ['student_id', 'stage', 'status'], unique=False)

    op.create_table('daily_revision_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('juz', sa.Integer(), nullable=False),
    sa.Column('method', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('logged_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('local_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('daily_revision_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_revision_logs_local_date'), ['local_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_revision_logs_student_id'), ['student_id'], unique=False)
        batch_op.create_index('ix_revision_student_date', ['student_id', 'local_date'], unique=False)
        batch_op.create_index('ix_revision_student_juz_date', ['student_id', 'juz', 'local_date'], unique=False)

    op.create_table('murajaat_classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('muhaffiz_id', sa.Integer(), nullable=True),
    sa.Column('juz', sa.Integer(), nullable=False),
    sa.Column('portion', sa.String(length=16), nullable=False),
    sa.Column('outcome', sa.String(length=16), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('local_date', sa.Date(), nullable=False),
    sa.Column('graded_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['muhaffiz_id'], ['muhaffiz_profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('murajaat_classes', schema=None) as batch_op:
        batch_op.create_index('ix_murajaat_class_student_date', ['student_id', 'local_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_murajaat_classes_local_date'), ['local_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_murajaat_classes_student_id'), ['student_id'], unique=False)

    op.create_table('murajaat_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('juz', sa.Integer(), nullable=False),
    sa.Column('portion', sa.String(length=16), nullable=False),
    sa.Column('weekday', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'weekday', 'juz', 'portion', name='uq_murajaat_plan_slot')
    )
    with op.batch_alter_table('murajaat_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_murajaat_plans_student_id'), ['student_id'], unique=False)

    op.create_table('page_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('page', sa.Integer(), nullable=False),
    sa.Column('juz', sa.Integer(), nullable=False),
    sa.Column('memorized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('memorized_on', sa.Date(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('signed_off_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('signed_off_by_muhaffiz_id', sa.Integer(), nullable=True),
    sa.Column('returned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stage2_entered_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['signed_off_by_muhaffiz_id'], ['muhaffiz_profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'page', name='uq_student_page')
    )
    with op.batch_alter_table('page_progress', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_page_progress_juz'), ['juz'], unique=False)
        batch_op.create_index(batch_op.f('ix_page_progress_student_id'), ['student_id'], unique=False)
        batch_op.create_index('ix_page_progress_student_juz', ['student_id', 'juz'], unique=False)

    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('issued_by_muhaffiz_id', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['issued_by_muhaffiz_id'], ['muhaffiz_profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_password_reset_tokens_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_password_reset_tokens_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_reset_user', ['user_id', 'used_at'], unique=False)

    op.create_table('student_juz',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('juz', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(length=16), nullable=False),
    sa.Column('memorization_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('memorization_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stage2_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stage2_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('juz_tasmee_passed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('juz_tasmee_passed_by_id', sa.Integer(), nullable=True),
    sa.Column('tasmee_window_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tasmee_attempt', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['juz_tasmee_passed_by_id'], ['muhaffiz_profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'juz', name='uq_student_juz')
    )
    with op.batch_alter_table('student_juz', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_juz_student_id'), ['student_id'], unique=False)

    op.create_table('tasmee_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('muhaffiz_id', sa.Integer(), nullable=True),
    sa.Column('stage', sa.String(length=16), nullable=False),
    sa.Column('juz', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('local_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['muhaffiz_id'], ['muhaffiz_profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tasmee_sessions', schema=None) as batch_op:
        batch_op.create_index('ix_tasmee_muhaffiz', ['muhaffiz_id', 'occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasmee_sessions_local_date'), ['local_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasmee_sessions_student_id'), ['student_id'], unique=False)
        batch_op.create_index('ix_tasmee_student_stage_date', ['student_id', 'stage', 'local_date'], unique=False)

    op.create_table('weak_spots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('juz', sa.Integer(), nullable=False),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_by_muhaffiz_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_muhaffiz_id'], ['muhaffiz_profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('weak_spots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_weak_spots_student_id'), ['student_id'], unique=False)
        batch_op.create_index('ix_weakspot_student_open', ['student_id', 'resolved_at'], unique=False)

    op.create_table('tasmee_page_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('page', sa.Integer(), nullable=False),
    sa.Column('juz', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(length=16), nullable=False),
    sa.Column('hifz_pass', sa.Boolean(), nullable=True),
    sa.Column('makharij_pass', sa.Boolean(), nullable=True),
    sa.Column('tajweed_pass', sa.Boolean(), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['tasmee_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tasmee_page_results', schema=None) as batch_op:
        batch_op.create_index('ix_result_session', ['session_id'], unique=False)
        batch_op.create_index('ix_result_student_page_passed', ['student_id', 'page', 'passed', 'recorded_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasmee_page_results_juz'), ['juz'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasmee_page_results_page'), ['page'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasmee_page_results_student_id'), ['student_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasmee_page_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tasmee_page_results_student_id'))
        batch_op.drop_index(batch_op.f('ix_tasmee_page_results_page'))
        batch_op.drop_index(batch_op.f('ix_tasmee_page_results_juz'))
        batch_op.drop_index('ix_result_student_page_passed')
        batch_op.drop_index('ix_result_session')

    op.drop_table('tasmee_page_results')
    with op.batch_alter_table('weak_spots', schema=None) as batch_op:
        batch_op.drop_index('ix_weakspot_student_open')
        batch_op.drop_index(batch_op.f('ix_weak_spots_student_id'))

    op.drop_table('weak_spots')
    with op.batch_alter_table('tasmee_sessions', schema=None) as batch_op:
        batch_op.drop_index('ix_tasmee_student_stage_date')
        batch_op.drop_index(batch_op.f('ix_tasmee_sessions_student_id'))
        batch_op.drop_index(batch_op.f('ix_tasmee_sessions_local_date'))
        batch_op.drop_index('ix_tasmee_muhaffiz')

    op.drop_table('tasmee_sessions')
    with op.batch_alter_table('student_juz', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_juz_student_id'))

    op.drop_table('student_juz')
    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.drop_index('ix_reset_user')
        batch_op.drop_index(batch_op.f('ix_password_reset_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_password_reset_tokens_token_hash'))

    op.drop_table('password_reset_tokens')
    with op.batch_alter_table('page_progress', schema=None) as batch_op:
        batch_op.drop_index('ix_page_progress_student_juz')
        batch_op.drop_index(batch_op.f('ix_page_progress_student_id'))
        batch_op.drop_index(batch_op.f('ix_page_progress_juz'))

    op.drop_table('page_progress')
    with op.batch_alter_table('murajaat_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_murajaat_plans_student_id'))

    op.drop_table('murajaat_plans')
    with op.batch_alter_table('murajaat_classes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_murajaat_classes_student_id'))
        batch_op.drop_index(batch_op.f('ix_murajaat_classes_local_date'))
        batch_op.drop_index('ix_murajaat_class_student_date')

    op.drop_table('murajaat_classes')
    with op.batch_alter_table('daily_revision_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_revision_student_juz_date')
        batch_op.drop_index('ix_revision_student_date')
        batch_op.drop_index(batch_op.f('ix_daily_revision_logs_student_id'))
        batch_op.drop_index(batch_op.f('ix_daily_revision_logs_local_date'))

    op.drop_table('daily_revision_logs')
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.drop_index('ix_assignment_student_stage')
        batch_op.drop_index('ix_assignment_muhaffiz')

    op.drop_table('assignments')
    op.drop_table('student_profiles')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))
        batch_op.drop_index('ix_notification_user_unread')

    op.drop_table('notifications')
    op.drop_table('muhaffiz_profiles')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
