"""revision log portion

Revision ID: 275713b3cf25
Revises: 6f781e36c948
Created: 2026-08-19 09:08:38.440795
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '275713b3cf25'
down_revision: Union[str, None] = '6f781e36c948'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_revision_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('portion', sa.String(length=16), server_default='full', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_revision_logs', schema=None) as batch_op:
        batch_op.drop_column('portion')

    # ### end Alembic commands ###
