"""reminder categories

Revision ID: 6f781e36c948
Revises: 6aec0d8001e0
Created: 2026-08-19 08:17:12.597935
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '6f781e36c948'
down_revision: Union[str, None] = '6aec0d8001e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # server_default is required, not cosmetic: without it the database has no
    # value to put in these columns for rows that already exist, and refuses the
    # ALTER outright.
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notify_hifz', sa.Boolean(), nullable=False, server_default=sa.text('1')))
        batch_op.add_column(sa.Column('notify_activity', sa.Boolean(), nullable=False, server_default=sa.text('1')))
        batch_op.add_column(sa.Column('notify_progress', sa.Boolean(), nullable=False, server_default=sa.text('1')))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('notify_progress')
        batch_op.drop_column('notify_activity')
        batch_op.drop_column('notify_hifz')

    # ### end Alembic commands ###
